# .streamlit/secrets.toml
[openai]
API_KEY = "your_openai_api_key"
API_URL = "your_openai_api_url"
OPENAI_API_KEY = "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"
OPENAI_ENDPOINT = "your_openai_endpoint"

[huggingface]
HUGGINGFACE_API_TOKEN = "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"

[indiankanoon]
INDIANKANOON_API_TOKEN = "1c5800d8addc3aa46f7f8d559ebb569261b4c387"

[GROQ]
GROQ_API = "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"
